### ISSUE TITLE
Can't stop the proxy with CTRL+C?

### ISSUE THREAD

**Issue by CaledoniaProject** [p3nt4/Invoke-SocksProxy#1]
I'm unable to stop script with `CTRL + C`, can you help?

**Comment by CaledoniaProject** [comment]
And does not seem to work with CURL command, 

```
%> curl --socks5 172.16.177.120:8888 172.16.177.120
curl: (7) Failed to receive SOCKS5 connect request ack.
```

**Comment by p3nt4** [comment]
Concerning the Ctrl-C, you can start the proxy as a job. At the moment you would need to close the powershell window/kill the process.
I cant reproduce the issue with curl.
![image](https://user-images.githubusercontent.com/19682240/32816915-40fdf77a-ca0f-11e7-863b-a16fb024b751.png)

**Comment by manasmbellani** [comment]
Having a similar issue as @CaledoniaProject with curl. Have opened a separate issue with attachments.
