### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by barbadosa** [p3nt4/Invoke-SocksProxy#3]
This is pretty cool, to have socks 4/5 in one file, but if you use it with Firefox (or Chrome), the connections never get closed, so opening 5 pages eats up all ram and the proxy server becomes unresponsive.

**Comment by p3nt4** [comment]
Yes, it's not very stable yet. Its not meant to be a production tool but rather a quick hack to get through firewalls. I am trying to improve it though.
I have noticed different behaviors depending on the OS and browser. It worked the best with Windows 10 and FoxyProxy.
HTTP is never going to be perfect with this as multithreading in power shell in really inefficient. SSH and RDP work much better as examples.

**Comment by barbadosa** [comment]
Detecting end of data and closing the connection would be a good place to start. It uses a lot of CPU, RAM and it loads relatively slow, but it's OK. Because the CPU does finish processing and the pages do load in the end. The fact that it uses a lot of memory is fine too, for what it is, and at this stage, but let's release the memory when it's no longer needed. There is some code in place that checks client.Connected && server.Connected (or similar), but the client object must be reporting as connected, because the script never closes connections, even when I close the browser. I will try FoxyProxy, but I doubt the connections will close.

**Comment by p3nt4** [comment]
The script is supposed to close the connections when either the client or the server does it. I have noticed the memory leak though so its not working apparently.

**Comment by jpginc** [comment]
Looks like the issue is related to a while loop. I was able to use the script successfully by changing it to:

    $count= 0
    while($client.Connected -and $tmpServ.Connected -and $count -lt 100) {
        sleep -m 100;
        $count = $count + 1
    }

I'm not going to do a pull request because I don't really know what the loop is doing...

**Comment by p3nt4** [comment]
The loop is checking if the client and server are still connected. The script is supposed to disconnect both once one of them closes the connection. Sadly it does not always work and I do not know why.

Your solution works and will be valid for HTTP type protocols, however, if users are using the socksproxy for a statefull protocol such as RDP or SSH, the connection will be disconected after 10 seconds.

**Comment by p3nt4** [comment]
Improved performance and fixed the memory leak.
