### ISSUE TITLE
Bypassing the need to Port Forward from Router & to Open the Port in Firewall

### ISSUE THREAD

**Issue by barbadosa** [p3nt4/Invoke-SocksProxy#4]
Since it's Windows, and we are talking about home PCs in many cases, there is the problem of router not knowing which local IP to route to and Windows Firewall on the PC blocking incoming connections. So you can't connect to such a proxy server.

There is a technique of making the home PC running the proxy server program ("Invoke-SocksProxy" PowerShell module in this case) initiate the connection to an actual server, which is open to the world. And then we, the user, can connect to the server and give directions to the connected proxy server (running on home PC), and to route traffic that way. The actual, open-to-the-world server can also run Windows and PowerShell / .NET.

Let's say our open server has IP 1.1.1.1 and the home PC proxy server has IP 2.2.2.2.

We would use 1.1.1.1:22222 v4/v5 as SOCKS proxy credentials, but our IP would appear as 2.2.2.2 to the web services we connect to.

**Comment by p3nt4** [comment]
I dont understand the issue.
