### ISSUE TITLE
PowerShell vs C#

### ISSUE THREAD

**Issue by barbadosa** [p3nt4/Invoke-SocksProxy#5]
It's my understanding that both PowerShell and C# are .NET, just use different syntax.
It's also my understanding that it's Microsoft's Bash.

And it's basically meant for one-liners that can do stuff on the command line.

Why not just use C#? Just a curious question, I'm perfectly ok with it.

**Comment by p3nt4** [comment]
This is a security tool. This is not meant for production.

https://betanews.com/2016/04/13/hackers-and-powershell/
